# Generated by Django 4.2.7 on 2025-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('Wedding Planner', 'Wedding Planner'), ('Event Management Company', 'Event Management Company'), ('Community Organization', 'Community Organization'), ('Corporate Event Planner', 'Corporate Event Planner'), ('Individual Planner', 'Individual Planner'), ('Other', 'Other')], max_length=50),
        ),
    ]
