# Generated by Django 4.2.7 on 2025-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_whatsapp_number_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
