# Generated by Django 4.2.7 on 2025-08-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budgetitem_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='vendor_name',
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='api.vendor'),
        ),
    ]
