# Generated by Django 4.2.7 on 2025-08-13 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscriptionplan_user_avatar_user_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.usersubscription'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('payment_proof', models.URLField(blank=True, help_text='Upload payment receipt/proof')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Payment Submitted'), ('verified', 'Payment Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentrequest'),
        ),
    ]
